development:
  adapter: postgresql
  encoding: unicode
  database: potato-dev
  username: carolinejobe
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: potato-test
  username: carolinejobe
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: potato-prod
  username: carolinejobe
  pool: 5
