development:
  adapter: postgresql
  encoding: unicode
  database: my_database_development
  username: carolinejobe
  pool: 5
  
test:
  adapter: postgresql
  encoding: unicode
  database: my_database_test
  username: carolinejobe
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: my_database_production
  username: carolinejobe
  pool: 5
